name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd Proyecto
        dotnet restore
        cd cliente
        npm install
    
    - name: Build .NET and Angular projects
      run: |
        cd Proyecto
        dotnet build --configuration Release
        cd cliente
        ng build --configuration production
    
    - name: Deploy
      run: |
        echo "Add your deployment steps here"
